sudo: required
services:
  - docker


before_script:
  - docker build -t mohamedawni/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true mohamedawni/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  buckent_name: "elasticbeanstalk-us-east-1-271448861260"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


